
POST  https://sb-api.herokuapp.com/routines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmI4NWFmMGZkZjYwZWIzNzExN2YxYiIsImlhdCI6MTY4NDc5ODYzMn0.mo-Vbjmdl9jCCp0ukiat1pawnxcAUMTXdVjc_2qKyvw
Content-Type: application/json

{
    "start" : "11:30",
    "end" : "11:40",
    "days" : [false, true, true, true, true, true, false ],
    "user" : "646b85af0fdf60eb37117f1b"
}

###
POST https://sb-api.herokuapp.com/auth/login
Content-Type: application/json

{
    "email": "geral@smartbreak.com",
    "password" : "123123123"

}

//646b7a61cec499ffa20b6e82
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmI3YTYxY2VjNDk5ZmZhMjBiNmU4MiIsImlhdCI6MTY4NDg0OTg0Nn0.bJIVwjKOWFK4qgtEGgh4MgsZ8sbZmOY1uIoHiJlzsyk
###
POST http://localhost:80/auth/login
Content-Type: application/json

{
    "email": "ju@ju.ju",
    "password": "Jujujuju"

}
###
POST https://sb-api.herokuapp.com/auth/login
Content-Type: application/json

{
    "email" : "debugging@smartbreak.pt",
    "password" : "debugging123"
}

###
GET http://localhost:80/goals/organization/6421b220698e83946dc83fab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODYxNWY0NzIyODA0YTFjNGIyMzJiNyIsImlhdCI6MTY4NzQzOTk5MH0.7bmUU5VX4stxbeR0OBfoRJ5zndEUGsN7z-gqMXSmd4Q

###
POST http://localhost:80/goals/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODYxNWY0NzIyODA0YTFjNGIyMzJiNyIsImlhdCI6MTY4NzQzOTk5MH0.7bmUU5VX4stxbeR0OBfoRJ5zndEUGsN7z-gqMXSmd4Q
Content-Type:  application/json

{
    "description" : "Diminuir a temperatura dos ares condicionados em 3 graus JOANA",
    "destination" : "6489d38140fbfb19c4142462",
    "organization" : "6421b220698e83946dc83fab",
    "priority": 1,
    "date": "2023-07-30T00:00:00.000Z",
    "organization" : "6421b220698e83946dc83fab",
    "types": "Computer" ,
    "active" : true,
}

###
GET https://sb-api.herokuapp.com/emails

###
POST  https://sb-api.herokuapp.com/auth/register
Content-Type: application/json

{
    "email": "without_access@smartbreak.com",
    "password" : "123123123",
    "name" : "User",
    "surname" : "Test",
    "admin" : false,
    "department" : "DECA",
    "access" : false
}

###
GET https://sb-api.herokuapp.com/organizations/6421b220698e83946dc83fab
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ODlkMzgxNDBmYmZiMTljNDE0MjQ2MiIsImlhdCI6MTY4Njc3NTM3NX0.sHL05v6ODJFpvmJ9CVDgxvgehr6yVzpKr0KYQh2ue9E

###
PATCH  https://sb-api.herokuapp.com/users/646b7a61cec499ffa20b6e82
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmI3YTYxY2VjNDk5ZmZhMjBiNmU4MiIsImlhdCI6MTY4NDc3MjcwMn0.OKnvGF7y_65iBxYbtLxFoV5yNePo1lPZ0pSlFRCnagc
Content-Type: application/json

{
    "department" : "DECA"
}
###
DELETE https://sb-api.herokuapp.com/devices/646bb6e4b58368db7922365b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NmI4NWFmMGZkZjYwZWIzNzExN2YxYiIsImlhdCI6MTY4NDg0OTk0MH0.UoA0mDavgRucLVZiagXVG-XhowzBuzaI02wdyfXC5pc
