
PATCH http://localhost:4000/goals/642570d4ece7267df6d30b19
Content-Type: application/json

{
    "priority": 2
}

### 
GET http://localhost:4000/departments

###
GET http://localhost:4000/goals/localhost:4000/goals/inactive

###
GET http://localhost:4000/departments

###
GET http://localhost:4000/goals/filter=3&destination=6
###
DELETE http://localhost:4000/goals/64256e67dfb5e16663b62c8a